/* tslint:disable */
/* eslint-disable */
/**
 * Thalassa API
 * API for ocean data exploration and AI co-pilot
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface WelcomeResponse
 */
export interface WelcomeResponse {
    /**
     *
     * @type {string}
     * @memberof WelcomeResponse
     */
    message: string
}

/**
 * Check if a given object implements the WelcomeResponse interface.
 */
export function instanceOfWelcomeResponse(
    value: object
): value is WelcomeResponse {
    if (!('message' in value) || value['message'] === undefined) return false
    return true
}

export function WelcomeResponseFromJSON(json: any): WelcomeResponse {
    return WelcomeResponseFromJSONTyped(json, false)
}

export function WelcomeResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): WelcomeResponse {
    if (json == null) {
        return json
    }
    return {
        message: json['message'],
    }
}

export function WelcomeResponseToJSON(json: any): WelcomeResponse {
    return WelcomeResponseToJSONTyped(json, false)
}

export function WelcomeResponseToJSONTyped(
    value?: WelcomeResponse | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value
    }

    return {
        message: value['message'],
    }
}
